I wanted to write a fun lil ruby program
codyolsen/help-friend-learn-git pull request #2
Opened 2017-03-23 20:28 UTC by briantgale

2017-03-23 22:08 UTC, codyolsen requested changes
Please add correct filename and structure for ruby architecture.

2017-03-23 22:08 UTC, codyolsen commented on newfile.rb
> +end
yeah pretty sure this a 🍰  loop...

2017-03-24 00:34 UTC, briantgale commented on newfile.rb
> +end
Nope.

2017-03-24 00:53 UTC, codyolsen approved these changes

2017-03-24 00:53 UTC, codyolsen commented on newfile.rb
> +end
MKay

2017-03-24 16:21 UTC, merged